---
  - hosts: localhost
    tasks:
    - name: launching AWS instance using Ansible
      ec2:
        key_name: Madhu44
        instance_type: t2.micro
        image:   ami-04bde106886a53080
        region: ap-south-1
        wait: yes
        group: 'Madhu SG'
        count: 1
        vpc_subnet_id: subnet-6546af0e
        assign_public_ip: yes
      register: ec2

    - debug: 
        var: ec2.instances[0].public_ip

    - name: Set fact for the host 
      set_fact: 
        appserver: "{{ ec2.instances[0].public_ip }}"

    - name: Add EC2 to ansible Dynamic Inventory
      add_host:
        hostname: "{{ appserver }}"
        groupname: slavenode
        ansible_user: ubuntu
        ansible_python_interpreter: /usr/bin/python3
      become: yes

    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for:
        host: "{{ appserver }}"
        delay: 60
        port: 22

    - block:
        - name: Apt cache update
          apt:
            update_cache: yes

        - name: install docker
          apt:
            pkg: docker.io
            state: present
        
        - name: start docker service
          service:
            name: docker
            state: started
            enabled: true

        - name: Deploy application
          command: docker run -it -d -p 8081:8888 --name casestudy ailamadu/casestudy:1.0

        - debug:
             msg: "Application can be accessed with URL http://{{appserver}}:8081"
      delegate_to: "{{ appserver }}"
      become: true
